[package]
name = "csvline"
version = "0.1.0"
authors = ["Jeremy Huiskamp"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
clap = "2.33.3"