name: htmlesc

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup BATS
      run: sudo npm install -g bats
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: htmlesc
    - name: Run tests
      run: ./test.bats
      working-directory: htmlesc
