name: htmlesc

on:
  pull_request:
  push:

defaults:
  run:
    working-directory: htmlesc

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup BATS
      run: sudo npm install -g bats
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: ./test.bats
